### ISSUE TITLE
TODO List  Workshop Week 3 - Day 4

### ISSUE THREAD

**Issue by edacostagan** [training-practice-sofkau/C3-2023-Angular-Frontend-Uruguay#38]
TODO List for a nice weekend... 👍 

- [x] Make a TODO list
- [x] Import module httpClientModule.
- [x] Inject the HttpClient into the services.
- [x] Load the modules using lazy loading.
- [x] Show customer information ( GET ) WITH TOKEN.
- [x] Show customer account information ( GET ).
- [ ] You must be able to make a Deposit (POST).
- [x] Login (Sign-in).

Extras

- [ ] Do an update of whatever type.
- [ ] Make any delete.

Anything else???
