### ISSUE TITLE
Todo Reto Angular

### ISSUE THREAD

**Issue by matisouza** [training-practice-sofkau/C3-2023-Angular-Frontend-Uruguay#73]
- [x] changeTypeAccount
- [x] updateCustomer
- [x] createDocumetType
- [x] createDeposit
- [x] getHistoryDeposit
- [x] createTransfer
- [x] getHistoryIn ( optional pero hacer uno de los 3 para Transfer )
- [x] getHistoryOut ( optional pero hacer uno de los 3 para Transfer )
- [x] getHistory ( optional pero hacer uno de los 3 para Transfer )
- [x] cuando se registra por google se debe registrar en el backend también
